### ISSUE TITLE
Improve gitlint processing of commits

### ISSUE THREAD

**Issue by palmerj** [linz/template-python-hello-world#36]
At the moment gitlint is checking all commits against in the current branch against master: `gitlint --commits origin/master..` This can cause problems if users are directly committing to master (I know), or when PRs are squashed and merged to master and github automatically increases the message length (adds issue number on the end!)

What would be more robust is running it for a range of commits in the PR branch or against the last (or few?) commit in master.

Note I see github actions only have a crude way of getting the range of commits: https://github.community/t5/GitHub-Actions/How-to-get-the-full-range-of-commits-for-a-PR/td-p/45074

**Comment by dwsilk** [comment]
How about  `gitlint --commits ${{ github.base_ref }}..${{ github.event.pull_request.head.sha }}` ?

**Comment by dwsilk** [comment]
I suppose that will only work if PRs are enforced...

**Comment by dwsilk** [comment]
So I guess with `if: github.event_name == 'pull_request'` we could run the command above, and otherwise just run `gitlint` to lint the last commit?

There may still be a problem if a series of commits are made directly on remote/master and are then pushed to origin/master.. but we're disabling direct commits to master most of the time anyway so could treat that as an unsupported edge case. Would you be happy with that?

**Comment by palmerj** [comment]
Happy for that logic to only be applied during PRs. Yeah ok to leave master as an Edge case. Thanks
